github: [proyecto26, jdnichollsc]
open_collective: proyecto26
patreon: proyecto26
ko_fi: proyecto26
buy_me_a_coffee: jdnichollsc
custom: ["https://liberapay.com/proyecto26", "https://paypal.me/jdnichollsc"]
